### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by cipricus** [rigon/qmmp-plugin-youtube#1]
How is it supposed to be installed?

**Comment by rigon** [comment]
Hi, thanks for the question!

The plugin is not yet finished, that's why I don't have any description about how to be installed.
Currently, it is possible to search for musics on youtube and only some that play.
I didn't have the time to finish it, but I hope I will get it soon.

Even though, if you want to test it, you can extract the source code of QMMP and clone this repository inside of it. Then compile QMMP with cmake and copy the built file libyoutube.so to the General plugin folder of your current installation.
Is possible that you exeperince some problems to make it work.

Feel free to ask me anything else!

**Comment by rigon** [comment]
Hi,

I'm happy to announce the first working release of this project.
It is accessible here: https://github.com/rigon/qmmp-plugin-youtube/releases

In the project main page (https://github.com/rigon/qmmp-plugin-youtube) you can find all the information that you need to build the plugin.

Any feedback would be great!
